More testing

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -27,8 +27,6 @@ jobs:
         run: |
           echo "cache hit! :)"
           cargo set-version -V
-          cd /home/linuxbrew/.linuxbrew/Cellar
-          ls
       - name: Install cargo edit
         if: steps.cache-cargo-edit.outputs.cache-hit != 'true'
         run: |
@@ -39,18 +37,24 @@ jobs:
       - name: Show install
         run: |
           which cargo
-          ls /home/linuxbrew/
+          ls /home/linuxbrew/.linuxbrew/bin/cargo
         shell: bash
       - name: Change version
         working-directory: cargo-testing-version
         run: |
-          cargo set-version --bump minor
+          echo "$( 
+            cargo set-version --bump minor
+          )"
+          echo "NEW_CRATE_VERSION_VERBOSE=$( 
+            cargo set-version --bump minor
+          )" >> $GITHUB_ENV
+          echo "${{ toJSON(env.NEW_CRATE_VERSION_VERBOSE) }}"
           echo "NEW_CRATE_VERSION=$( 
             cargo set-version --bump minor | awk 'NR==1 {print $NF}' 
           )" >> $GITHUB_ENV
       - name: Check version set
         if: env.NEW_CRATE_VERSION == ''
-        run: echo "Empty version :(" >&2
+        run: ">&2 echo 'error no version'"
         shell: bash
       - name: Show new version
         run: echo "New version ${{ env.NEW_CRATE_VERSION }}"
